name: smoke-testing

# 指定觸發條件
on:
  # 僅允許手動執行
  workflow_dispatch:

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-modules.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ steps.cache-modules.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-node-

  install-dependencies:
    needs: setup-cache
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ needs.setup-cache.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

  unit-test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ needs.setup-cache.outputs.cache-key }}

      - name: Run unit testing with coverage
        run: yarn lerna run test:cov

  end-to-end-test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ needs.setup-cache.outputs.cache-key }}

      - name: Run end-to-end testing
        run: yarn lerna run test:e2e

  build:
    needs: [unit-test, end-to-end-test]
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ needs.setup-cache.outputs.cache-key }}

      - name: Compile TypeScript code to JavaScript code
        run: yarn lerna run build
# jobs:
#   smoke-test:
#     runs-on: ubuntu-latest
#     container: node:18-bullseye
#     steps:
#       - uses: actions/checkout@v2 # 確認 checkout 是否過舊

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "18"

#       - name: Cache Node.js modules
#         uses: actions/cache@v2 # 確認 cache 是否過舊
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - name: Install dependencies
#         run: yarn install

#       - name: Run unit testing with coverage
#         run: yarn lerna run test:cov #--since=origin/main

#       - name: Run end-to-end testing
#         run: yarn lerna run test:e2e #--since=origin/main

#       - name: Compile TypeScript code to JavaScript code
#         run: yarn lerna run build #--since=origin/main
