name: smoke-testing

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Generate cache key
        id: cache-keys
        run: echo "::set-output name=cache-key::$(date +%s)"

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: ${{ needs.setup.outputs.cache-key }}

      - name: Run unit testing with coverage
        run: yarn lerna run test:cov #--since=origin/main

  e2e-test:
    needs: setup
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: ${{ needs.setup.outputs.cache-key }}

      - name: Run end-to-end testing
        run: yarn lerna run test:e2e #--since=origin/main

  build:
    needs: setup
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: ${{ needs.setup.outputs.cache-key }}

      - name: Build code
        run: yarn lerna run build #--since=origin/main
