name: smoke-testing

on:
  workflow_dispatch:
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run unit testing with coverage
        run: yarn lerna run test:cov #--since=origin/main

      - name: Run end-to-end testing
        run: yarn lerna run test:e2e #--since=origin/main

      - name: Build code
        run: yarn lerna run build #--since=origin/main
