name: smoke-testing

on:
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: unit-testing
          - task: e2e-testing
          - task: build
    container: node:18-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run unit testing with coverage
        if: matrix.task == 'unit-testing'
        run: yarn lerna run test:cov #--since=origin/main

      - name: Run end-to-end testing
        if: matrix.task == 'e2e-testing'
        run: yarn lerna run test:e2e #--since=origin/main

      - name: Build code
        if: matrix.task == 'build'
        run: yarn lerna run build #--since=origin/main
